name: linux build 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build
      run: |
        OUTPUT=build/output
        mkdir -p $OUTPUT
        echo linux-debug > $OUTPUT/nzbget-22.0-bin-linux-debug.run
        echo linux > $OUTPUT/nzbget-22.0-bin-linux.run

    - name: Rename build artifacts
      if: github.ref_name != 'main'
      run: |
        cd build/output
        VERSION=$(ls | grep bin-linux.run | cut -d - -f 2)
        NEW_VERSION="$VERSION-testing-$(date '+%Y%m%d')"
        if [ "$GITHUB_REF_NAME" != "develop" ]; then
          NEW_VERSION="$NEW_VERSION-${GITHUB_REF_NAME/\//-}"
        fi
        for FILE in *.run; do
          [ -f $FILE ] || continue
          NEW_FILE=${FILE/$VERSION/$NEW_VERSION}
          mv $FILE $NEW_FILE          
        done

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nzbget-linux-installers
        path: build/output/*.run
        retention-days: 5

    - name: Cleanup
      run: |
        rm -rf /build/nzbget
        rm -rf /build/output
