name: linux build 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build
      run: |
        OUTPUT=build/output
        mkdir -p $OUTPUT
        echo linux-debug > $OUTPUT/nzbget-22.0-bin-linux-debug.run
        echo linux > $OUTPUT/nzbget-22.0-bin-linux.run

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nzbget-linux-installers
        path: build/output/*.run
        retention-days: 5

    - name: Cleanup
      run: |
        rm -rf /build/nzbget
        rm -rf /build/output
