name: osx build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build
      run: |
        mkdir -p osx/build/Release
        echo macos > osx/build/Release/nzbget-22.0-bin-macos.zip

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nzbget-osx-installers
        path: osx/build/Release/*.zip
        retention-days: 5
