name: windows build 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        OUTPUT=build/output
        mkdir -p $OUTPUT
        echo windows-debug > $OUTPUT/nzbget-22.0-bin-windows-debug-setup.exe
        echo windows > $OUTPUT/nzbget-22.0-bin-windows-setup.exe

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nzbget-windows-installers
        path: build/output/*.exe
        retention-days: 5
