name: windows build 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        $Output="c:\nzbget\build\output"
        New-Item -Path $Output -ItemType Directory -Force
        "windows-debug" | Out-File $Output/nzbget-22.0-bin-windows-debug-setup.exe
        "windows" | Out-File $Output/nzbget-22.0-bin-windows-setup.exe

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nzbget-windows-installers
        path: C:\nzbget\build\output\*.exe
        retention-days: 5
